//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automobile_Accounting.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class avto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public avto()
        {
            this.order = new HashSet<order>();
        }
    
        public int ID { get; set; }
        public int id_avto { get; set; }
        public string serial_number { get; set; }
        public string brend { get; set; }
        public string model { get; set; }
        public string configuration { get; set; }
        public int year { get; set; }
        public string kuzov { get; set; }
        public string color { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> order { get; set; }
    }
}
