//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automobile_Accounting.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int ID { get; set; }
        public int num_order { get; set; }
        public System.DateTime date_order { get; set; }
        public string name_brend { get; set; }
        public string name_model { get; set; }
        public string name_configuration { get; set; }
        public string name_color { get; set; }
        public string quantity_avto { get; set; }
        public decimal sum_sale { get; set; }
        public string name_partner { get; set; }
        public string fio_partner { get; set; }
        public decimal discount { get; set; }
        public Nullable<decimal> sum_sale_discount { get; set; }
        public Nullable<bool> contract { get; set; }
        public Nullable<int> ID_avto { get; set; }
        public Nullable<int> ID_partners { get; set; }
        public Nullable<int> ID_reports { get; set; }
        public Nullable<int> ID_role { get; set; }
    
        public virtual avto avto { get; set; }
        public virtual partners partners { get; set; }
        public virtual report report { get; set; }
        public virtual role role { get; set; }
    }
}
